import type { Metadata } from "next";
import Link from "next/link";
import { Calculator } from "@/components/calculator";
import { JsonLd } from "@/components/json-ld";
import { CHALDEAN_GROUPS } from "@/data/chaldean";
import { ROOT_MEANINGS } from "@/data/interpretations";
import { homeFaqs } from "@/content/faqs";
import { siteConfig } from "@/config/site";
import { AuthorCard } from "@/components/author-card";

export const metadata: Metadata = { title: { absolute: siteConfig.title }, description: siteConfig.description, alternates: { canonical: "/" }, openGraph: { title: siteConfig.title, description: siteConfig.description, url: "/", siteName: siteConfig.name, type: "website", images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: "Chaldean Numerology Calculator with an eight-point orbit motif" }] }, twitter: { card: "summary_large_image", title: siteConfig.title, description: siteConfig.description, images: ["/opengraph-image"] } };

export default function Home() {
  const faqEntities = homeFaqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } }));
  return <><JsonLd data={[{ "@context": "https://schema.org", "@type": "WebSite", name: siteConfig.name, url: siteConfig.url, publisher: { "@type": "Person", name: "Arslan Ejaz" } }, { "@context": "https://schema.org", "@type": "WebPage", name: siteConfig.title, description: siteConfig.description, url: siteConfig.url, author: { "@type": "Person", name: "Arslan Ejaz" } }, { "@context": "https://schema.org", "@type": "WebApplication", name: siteConfig.name, url: siteConfig.url, applicationCategory: "LifestyleApplication", browserRequirements: "Requires JavaScript for interactive calculation", operatingSystem: "Any modern web browser", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, description: "A free browser-based Chaldean name, birth, and life-path number calculator." }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqEntities }]} />
    <header className="hero"><div className="container hero-grid"><div><h1>Chaldean Numerology Calculator</h1><p>Discover your name number with the traditional 1-to-8 letter chart. See the complete compound total and root number, then add a birth date for optional Birth and Life Path numbers.</p></div><div className="orbit" aria-hidden="true"><strong>1–8</strong></div></div></header>
    <Calculator/>
    <section className="section"><div className="narrow"><p>Want to check the method by hand? Read <Link href="/blog/how-to-calculate-name-number-chaldean-numerology/">how to calculate a name number in Chaldean numerology</Link>.</p></div></section>
    <section className="section alt"><div className="container"><p className="eyebrow">A transparent method</p><h2>How the Chaldean Numerology Calculator Works</h2><p className="lede">A Name Number is the total assigned to the entered name in this traditional system. A date adds two separate lenses. These interpretations are used for entertainment and personal reflection, not scientific diagnosis or prediction.</p><div className="card-grid"><article className="card"><span className="step-number">01</span><h3>Normalize the name</h3><p>Accented Latin letters are reduced to their base form. Spaces and ordinary punctuation separate name parts but add no value.</p></article><article className="card"><span className="step-number">02</span><h3>Assign letter values</h3><p>Each A-to-Z letter receives the value shown in the traditional 1-to-8 chart. The result displays each assignment.</p></article><article className="card"><span className="step-number">03</span><h3>Keep the compound</h3><p>Every letter and word subtotal forms the unreduced compound number. This number is never discarded.</p></article><article className="card"><span className="step-number">04</span><h3>Reduce to a root</h3><p>Digits are added repeatedly until 1 through 9 remains. Optional date numbers use the calendar day and all date digits.</p></article></div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Reference chart</p><h2>Chaldean Numerology Letter Chart</h2><div className="table-wrap" role="region" aria-label="Chaldean letter chart" tabIndex={0}><table><thead><tr><th>Value</th><th>Latin letters</th></tr></thead><tbody>{Object.entries(CHALDEAN_GROUPS).map(([value, letters]) => <tr key={value}><td><strong>{value}</strong></td><td>{letters.join(" · ")}</td></tr>)}</tbody></table></div><p>No letter receives 9 in this commonly published chart. Nine is still a valid calculated result, such as JOHN: 18 → 9. <Link href="/chaldean-numerology-chart/">Read the chart rules and more examples</Link>.</p></div></section>
    <section className="section alt"><div className="container"><div className="card-grid"><article className="card"><p className="eyebrow">Worked example</p><h2>ALICE is 13/4</h2><p>A1 + L3 + I1 + C3 + E5 = 13. Then 1 + 3 = 4. The compound 13 and root 4 are shown together rather than reducing each name part too early.</p></article><article className="card"><p className="eyebrow">Use the name you know</p><h2>Which name should you enter?</h2><p>Many Cheiro-style practitioners focus on the name commonly used by other people. Compare a legal name, everyday name, nickname, or changed spelling separately. This is a tradition, not a proven causal mechanism.</p></article><article className="card"><p className="eyebrow">System matters</p><h2>Chaldean is not Pythagorean</h2><p>The charts, treatment of 9, compound emphasis, and master-number rules can differ. <Link href="/chaldean-vs-pythagorean-numerology/">See why calculators return different answers</Link>.</p></article></div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Three distinct calculations</p><h2>Name Number, Birth Number, and Life Path Number</h2><div className="table-wrap" role="region" aria-label="Numerology calculation comparison" tabIndex={0}><table><thead><tr><th>Number</th><th>Input used</th><th>Calculation</th><th>Common reflective use</th></tr></thead><tbody><tr><td>Name Number</td><td>Entered name</td><td>Chaldean letter total</td><td>Expression and personality themes</td></tr><tr><td>Birth Number</td><td>Calendar day</td><td>Day reduced, such as 24/6</td><td>Day-of-birth tendencies</td></tr><tr><td>Life Path Number</td><td>Full birth date</td><td>Every date digit added</td><td>A broad path or development theme</td></tr></tbody></table></div><p>Some schools call the name-derived result a Destiny Number, while others use Destiny or Life Path for the full-date result. This calculator labels both the input and method so the terminology cannot hide the calculation.</p></div></section>
    <section className="section alt"><div className="container"><p className="eyebrow">Balanced themes</p><h2>What Numbers 1 to 9 Commonly Represent</h2><div className="number-grid">{ROOT_MEANINGS.map((item) => <article key={item.number} className="meaning-mini"><strong>{item.number}. {item.title}</strong><p>{item.overview}</p></article>)}</div><p><Link href="/numerology-number-meanings/">Explore strengths, growth areas, prompts, and traditional planetary associations</Link>.</p></div></section>
    <section className="section"><div className="container"><h2>Common Calculation Mistakes</h2><div className="card-grid"><article className="card"><h3>Mixing charts</h3><p>Using a Pythagorean value or assigning a letter to 9 changes the result while still appearing plausible.</p></article><article className="card"><h3>Losing the compound</h3><p>Reducing word parts early, or silently stopping at 11, 22, or 33, obscures the strict method used here.</p></article><article className="card"><h3>Guessing at input</h3><p>Punctuation has no value, and non-Latin names need a transliteration chosen by the person, not a silent automated guess.</p></article></div></div></section>
    <section className="section alt"><div className="narrow"><h2>Limits and Responsible Use</h2><p>Numerology is an esoteric or spiritual belief system. It is not a scientifically validated diagnostic or predictive method, and interpretations differ among Chaldean, Cheiro, and modern Indian schools. Use a result as a reflective prompt, not as a substitute for medical, legal, financial, mental-health, relationship, career, or other professional advice.</p><p>Historical context can be found in the digitized <a href="https://archive.org/download/cheirosbookofnumbers/Cheiro%27s%20Book%20of%20Numbers_text.pdf" target="_blank" rel="noopener noreferrer">text of Cheiro’s Book of Numbers</a>. For broader context, see an <a href="https://www.encyclopedia.com/philosophy-and-religion/other-religious-beliefs-and-general-terms/miscellaneous-religion/numerology" target="_blank" rel="noopener noreferrer">encyclopedia overview of numerology</a>. Historical claims in numerology literature should be read as claims from that tradition, not established archaeological fact.</p></div></section>
    <section className="section"><div className="narrow"><p className="eyebrow">Frequently asked questions</p><h2>Questions about the calculator</h2><div className="faq-list">{homeFaqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div><AuthorCard/></div></section>
  </>;
}
